### ISSUE TITLE
Anxiously awating...

### ISSUE THREAD

**Issue by the-butterfry** [hemtjanst/hallonlarm#1]
Well done on this! I'm a raspberry newb and totally am not qualified to do what it takes to get this built and installed. 
With the proliferation of wifi enabled switches out there this script will be great for translating traditional RPi GPIO based programs quickly and seamlessly to wireless devices!

I'm trying to build a controller for my hot tub. I'm using someone else's code built with GPIO, with your script i'll be able to map the existing GPIO structure directly to my MQTT switches.... 
All that said... a little help getting this built and installed from your latest commits?
thanks!

**Comment by bonan** [comment]
I've added travis and goreleaser and tagged a [release](https://github.com/hemtjanst/hallonlarm/releases/tag/v0.1.0) with install instructions.

**Comment by the-butterfry** [comment]
Thanks :) I was able to get it installed no problem, from the previous release. It was the Go building instructions that are provided that I was struggling with. Was having dependency issues, but it was probably my fault. I've never built anything with Go.

**Comment by bonan** [comment]
Great that you got it working :)

I've updated the readme to add a note about using `dep` for dependency management.

Closing this issue now, but feel free to open a new one if you notice any bugs - as I have not myself actually tested GPIO output yet, only input

**Comment by the-butterfry** [comment]
Thanks!
Here's hallonlarm in action https://github.com/the-butterfry/Oasis-Spa/wiki
